# -*- coding: utf-8 -*-
"""Data Preprocessing using Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y089w26Y_trF4uwdW19QyPu4ImZ_oTDg

### Pandas
"""

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Spring 2026/AI Lab/diabetes_prediction_dataset.csv'

import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(0,20).reshape(5,4))
df.head() # shows the first 5 rows in the dataset

import pandas as pd

data = pd.read_csv(file_path)

data.shape

# print(data.head(2)) # shows the first 2 rows in the dataframe
print(data.info()) # shows detailed information of the dataframe
print(data.isnull().sum())
# print(data.describe())  # shows stats of columns

"""## Indexing"""

# loc and iloc
data.loc[0]['bmi'] # shows row information

data.iloc[:5,-4:-1]

## Accessing the elements
## 1. loc 2. iloc
print(df.loc['B'])

print(df.iloc[:2,:2])
print(df.iloc[1:3,1:3])

"""## Replacing Missing values"""

# replace with the average value of the
data['bmi'].isna().sum()
print(data['bmi'].mean())
data['bmi'].fillna(data['bmi'].mean(),inplace=True)
data['bmi'].head(10)

data['HbA1c_level'].fillna(data['HbA1c_level'].ffill(),inplace=True)

data['HbA1c_level'][6]

data['blood_glucose_level'].fillna(data['blood_glucose_level'].bfill(),inplace=True)

data.isna().sum()

data.to_csv(file_path)

"""#### Working with CSV"""

# create csv from string
from io import StringIO, BytesIO
data = ('col1,col2,col3\n'
        'x,y,1\n'
        'a,b,2\n'
        'c,d,3')
df = pd.read_csv(StringIO(data))
print(df.head())
df2 = pd.read_csv(StringIO(data),usecols=['col1','col3'])
print(df2.head())
df.to_csv('Test.csv')

# Specifying columns data types
data = ('a,b,c,d\n'
        '1,2,3,4\n'
        '5,6,7,8\n'
        '9,10,11')
df = pd.read_csv(StringIO(data),dtype=object)
print(df.head())
print(df['a'][1])
df = pd.read_csv(StringIO(data),dtype={'b':int,'c':float,'a':'Int64'})
print(df.head())
print(df.dtypes)

# Index columns and training delimiters
data = ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,10')
df = pd.read_csv(StringIO(data))
print(df.head())
df = pd.read_csv(StringIO(data),index_col=0)
print(df.head())
data = ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow,')
df = pd.read_csv(StringIO(data),index_col=False)
print(df.head())

# Combining usecols and index_col
data = ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow,')
df = pd.read_csv(StringIO(data),usecols=['b','c'],index_col=False)
print(df.head())

# Quoting and Escape characters. Very useful in NLP
data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'
df = pd.read_csv(StringIO(data),escapechar='\\')
print(df.head())

"""#### Reading JSON"""

data='{ "employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead","title2":"Sr. Developer"}]}'
df1 = pd.read_json(data)
df1.head()
df2 = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',header=None)
df2.head()

# convert json to csv
df1.to_csv('employee.csv')
df2.to_csv('wine.csv')

# convert json to different json formats
# df1.to_json()
# df1.to_json(orient="index")
df1.to_json(orient="records")
df2.to_json(orient="records",lines=True)

"""#### Reading HTML"""

url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'
dfs = pd.read_html(url_mcc,match='Country',header=0)
dfs[0]

"""#### Reading Excel"""

fw = pd.read_excel('Farewell List.xlsx',header=0)
fw

"""#### Pickling"""

fw.to_pickle('fw_pickle')
fw_pickle = pd.read_pickle('fw_pickle')
fw.head()

"""### Matplotlib"""

# Matplotlib
import matplotlib.pyplot as plt

x = np.arange(0,10)
y = np.arange(11,21)

plt.scatter(x,y,c='r')
plt.xlabel('X axis')
plt.ylabel('Y axis')
plt.title('2D Graph')

y1 = x*x
plt.plot(x,y1,'bx-',linewidth=1,markersize=3)
plt.legend(['X','X^2'])

## Creating subplots
plt.subplot(2,2,2)
plt.plot(x,y,'ro-')
plt.subplot(2,2,1)
plt.plot(x,y,'g*--')

## Compute x and y coordinates for points on sine and cosine curves
x = np.arange(0,4*np.pi,0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)
plt.subplot(2,1,1)
plt.plot(x,y_sin,'r-')
plt.title('Sine')
plt.subplot(2,1,2)
plt.plot(x,y_cos,'g-')
plt.title('Cosine')

### Bar plot
x = [2,8,10]
y = [11,16,9]

x2 = [3,9,11]
y2 = [6,15,7]
plt.bar(x,y)
plt.bar(x2,y2,color='g')
plt.title('Bar Graph')
plt.xlabel('X axis')
plt.ylabel('Y axis')

### Histograms
a = np.array([22,87,5,43,56,73,55,54,11,20,51,5,79,31,27])
plt.hist(a,bins=20)
plt.title('Histogram')
plt.xlabel('X axis')
plt.ylabel('Y axis')

### Box plot
data = [np.random.normal(0,std,100) for std in range(1,4)]
plt.boxplot(data,vert=True,patch_artist=True)
plt.title('Box Plot')

### Pie chart
labels = 'Python','C++','Ruby','Java'
sizes = [215,130,245,210]
colors = ['gold','yellowgreen','lightcoral','lightskyblue']
explode = (0.05,0.05,0.05,0.05)
# explode=[0,0,0,0]
plt.pie(sizes,explode=explode,labels=labels,colors=colors,autopct='%1.1f%%',shadow=True)
plt.axis('equal')

"""### Seaborn"""

import seaborn as sns

df = sns.load_dataset('tips')
df.head()